export const Constant = {
    ANDREW :`Andrew had a brilliant idea: a cozy café where books would be traded alongside coffee aromas. He imagined it—a place where bookworms and coffee lovers could unite, sharing stories and sipping warmth.

    But life's whirlwind swept him away. Responsibilities piled up, and doubts whispered that his idea was just a dream. Days turned into years, and Andrew watched others open similar cafes, flourishing and fostering communities.
    
    One afternoon, while sipping his latte in a bustling book café, regret lingered. He realized it could've been his laughter echoing off those walls, his joy sharing stories with patrons. A pang of remorse surged; he never dared to bring his concept to life.`,
    CLOCK_TICKING:`Tick-Tock, Your Opportunity Awaits!
    In the race against time, your big idea is waiting to break free and redefine the world. The clock's hands are moving fast, and so should you—don't let the precious moments slip away. Join our platform, where the challenge of transforming your idea into a thriving business meets unwavering support and tailored guidance. Time is our greatest asset, and every second counts on this entrepreneurial journey. Embrace the urgency, click below, and take charge of your destiny before the ticking clock turns into missed possibilities!`,
    DARE_YOU:`We're not looking for those content with 'someday' or 'maybe.' No, we seek the bold, the dreamers ready to take the leap into entrepreneurship. Are you the fearless soul who dares to challenge the status quo? Those who step forward, ready to convert their vision into reality, embracing risk as a companion on this exhilarating journey. We invite the courageous, the bold-hearted, those unafraid of uncertainty, to join us. Let's defy the 'what-ifs' together and carve success out of your idea. Are you ready to be the architect of your destiny? If so, we dare you: start now and let's make your dream business a vibrant reality!`,
    TAKE_ACTION:`To truly understand how our system can assist you, you need to experience it firsthand. If you're unwilling to seize this opportunity, it might explain any hesitation in starting your business. If you've reached this section without intending to click any button, perhaps this isn't the right fit for you. We wish you the best on your journey of dreaming about a business from your idea, while others take action to bring theirs to life.

    However, if you're ready to take action and try our system, remember to share your success story with us and others. You're the one who can inspire a thousand others who might just need a little push to begin their own journey`,
    EMAIL_VERIFIED:`An email has been sent to verify your email address. If you haven't received it yet, you can click the 'Resend' button below. If you've already verified your email, please proceed by clicking the 'Login' button below.`,
    ea8423a2:{id:'ideaGeneration',name:'Idea Generation'},
    fff72284:{id:'ideaValidation',name: 'Idea Validation'},
    aff35e0:{id:'marketResearch',name:'Market Research'},
    a486c9c1:{id:'businessPlan',name:'Business Plan'},
    targetAudience:'Target Audience',
    problemSolutionFit:'Problem-Solution Fit',
    competitiveAnalysis:'Competitive Analysis',
    intellectualProperty:'Intellectual Property',
    regulatoryLegalConsideration:'Regulatory & Legal Consideration',
    researchRequirement:'Research Requirement',
    marketDemand:'Market Demand',
    uniqueness:'Uniqueness',
    feasibility:'Feasibility',
    competitorAnalysis:'Competitor Analysis',
    productServiceValidation:'Product/Service Validation',
    marketingDistribution:'Marketing & Distribution',
    demographics:'Demographics',
    psychographics:'Psychographics',
    directCompetitors:'Direct Competitors',
    indirectCompetitors:'Indirect Competitors',
    featuresBenefits:'Features & Benefits',
    customerFeedbackValidation:'Customer Feedback & Validation',
    marketingChannels:'Marketing Channels',
    distributionStrategy:'Distribution Strategy',
    executiveSummary:'Executive Summary',
    companyDescription:'Company Description',
    marketAnalysis:'Market Analysis',
    productsServices:'Products and Services',
    marketingPlan:'Marketing Plan',
    logisticsOperationsPlan:'Logistics and Operations Plan',
    financialPlan:'Financial Plan',
    businessOverview:'Business Overview',
    goalsObjectives:'Goals and Objectives',
    bpTargetAudience:'Target Audience',
    businessVision:'Business Vision',
    foundingStory:'Founding Story',
    valuesCulture:'Values and Culture',
    legalStructureteam:'Legal Structure and Team',
    socialEnvironmentalImpact:'Social/Environmental Impact',
    bpCompetitorAnalysis:'Competitor Analysis',
    industryTrends:'Industry Trends',
    targetMarket:'Target Market',
    riskAssessment:'Risk Assessment',
    offeringsDescription:'Offerings Description',
    uniqueSellingProposition:'Unique Selling Proposition (USP)',
    pricingStrategy:'Pricing Strategy',
    qualityAssurance:'Quality Assurance',
    channelStrategy:'Channel Strategy',
    brandingMessaging:'Branding and Messaging',
    performanceMeasurement:'Performance Measurement',
    partnershipsCollaborations:'Partnerships and Collaborations',
    supplyChainProduction:'Supply Chain and Production',
    technologicalInfrastructure:'Technological Infrastructure',
    staffingManagement:'Staffing and Management',
    qualityControl:'Quality Control',
    startupCostsExpenses:'Startup Costs and Expenses',
    revenueProjections:'Revenue Projections',
    breakEvenAnalysis:'Break-even Analysis',
    costManagement:'Cost Management',
    newBorn:`Congratulations! Your baby has just born. Now, let's nurture and guide it as it begins to grow`,
    crawlBaby:`Fantastic progress! Your baby is now crawling along beautifully. Let's continue guiding its growth`,
    standBaby:`Well done! Your baby can stand on its own now. Let's support its next developmental phase`,
    walkingBaby:`Congratulations! Your baby is confidently taking its first steps. Let's keep fostering its progress!`,
    descIdeaValidation:`Validate Your Vision: Our Idea Validation feature asks targeted questions to refine and test your idea. Get tailored guidance to assess market fit and enhance your concept's potential for success`,
    descMarketResearch:`Explore Market Landscapes: Dive into our Market Research feature, guiding you through strategic questions to uncover valuable insights for your idea. Elevate your understanding of market dynamics and fine-tune your concepts for success.`,
    descBusinessPlan:`Blueprint for Success: Our Business Plan tool is your roadmap from idea to reality. By asking targeted questions, it guides you in formulating a comprehensive business plan, turning your vision into a strategic success story.`



}